"""
api/chat.py
────────────────────────────────────────────────────────────────────────────────
FastAPI router for the Q&A chat endpoint.

ENDPOINT:
  POST /api/chat

THE Q&A PIPELINE (inside this endpoint):

  User question (natural language)
       │
       ▼
  generate_cypher(question)        ← Gemini: NL → Cypher
       │  "MATCH (a)-[:CEO_OF]->(o) WHERE ..."
       ▼
  execute_cypher(cypher)           ← Neo4j: run the query
       │  [{"ceo": "Sam Altman", "org": "OpenAI"}]
       ▼
  generate_answer(question, results) ← Gemini: graph data → NL answer
       │  "Sam Altman is the CEO of OpenAI."
       ▼
  Return {answer, cypher, graph_results}

WHY RETURN CYPHER IN THE RESPONSE?
  Transparency — the user and developer can see exactly what query ran.
  This is important for a knowledge graph app because it makes the
  reasoning process inspectable. "Why did the app say that?"
  → Look at the Cypher. "What did Neo4j return?" → Look at graph_results.

WHY RETURN RAW GRAPH_RESULTS TOO?
  The Streamlit frontend can display them as a table alongside the
  natural language answer. This gives users the raw evidence behind
  the answer — important for trust and debugging.
────────────────────────────────────────────────────────────────────────────────
"""

import logging

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from graph.cypher_generator import generate_cypher
from graph.graph_query import execute_cypher
from llm.answer_generator import generate_answer

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Chat"])


# ── Request model ──────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    """
    Request body for the POST /chat endpoint.

    Fields:
        question (str):
            The user's natural language question about the knowledge graph.
            Examples:
              "Who created GPT-4?"
              "What companies is Elon Musk associated with?"
              "Which technologies does OpenAI use?"
    """
    question: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="Natural language question to ask the knowledge graph.",
        examples=["Who created GPT-4?", "What did OpenAI build?"],
    )


# ── Response model ─────────────────────────────────────────────────────────────

class ChatResponse(BaseModel):
    """
    Response from the POST /chat endpoint.

    Fields:
        answer (str):
            Human-readable answer generated by Gemini from the graph results.
            Example: "GPT-4 was created by OpenAI."

        cypher (str):
            The Cypher query that was generated and executed.
            Useful for transparency, debugging, and learning Cypher.
            Example: "MATCH (a)-[:CREATED]->(b) WHERE ... RETURN a.name"

        graph_results (list[dict]):
            Raw results returned by Neo4j before being converted to text.
            Useful for the frontend to display as a table.
            Example: [{"creator": "Openai", "product": "Gpt-4"}]

        question (str):
            The original question echoed back. Useful for the frontend
            to display in chat history without re-storing it client-side.
    """
    answer: str
    cypher: str
    graph_results: list[dict]
    question: str


# ── POST /chat ─────────────────────────────────────────────────────────────────

@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Ask a question about the knowledge graph",
    description=(
        "Accepts a natural language question, generates a Cypher query, "
        "executes it against Neo4j, and returns a natural language answer. "
        "Also returns the raw Cypher and graph results for transparency."
    ),
)
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Answers a natural language question using the knowledge graph.

    Pipeline:
      question → Cypher → Neo4j results → natural language answer.

    Args:
        request (ChatRequest): Contains the user's question.

    Returns:
        ChatResponse with answer, cypher, raw graph results, and question.

    Raises:
        400: If the question is empty or too short (handled by Pydantic).
        500: If Gemini or Neo4j fails at any step.
    """
    question = request.question.strip()

    logger.info("Chat request: '%s'", question)

    # ── Step 1: Generate Cypher from the question ─────────────────────────────
    try:
        cypher = generate_cypher(question)
        logger.info("Generated Cypher: %s", cypher)
    except RuntimeError as exc:
        logger.error("Cypher generation failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate Cypher query: {exc}",
        ) from exc

    # ── Step 2: Execute the Cypher against Neo4j ──────────────────────────────
    try:
        graph_results = execute_cypher(cypher)
        logger.info(
            "Cypher returned %d result(s) for question: '%s'",
            len(graph_results), question,
        )
    except Exception as exc:
        # The Cypher may be syntactically invalid — catch and return a
        # helpful error rather than crashing.
        logger.error("Cypher execution failed: %s | Query: %s", exc, cypher)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=(
                f"Failed to execute graph query. "
                f"The generated Cypher may be invalid. "
                f"Cypher: {cypher}"
            ),
        ) from exc

    # ── Step 3: Generate a natural language answer ────────────────────────────
    try:
        answer = generate_answer(question, graph_results)
        logger.info("Answer generated (%d chars)", len(answer))
    except RuntimeError as exc:
        logger.error("Answer generation failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate answer from graph results: {exc}",
        ) from exc

    return ChatResponse(
        answer=answer,
        cypher=cypher,
        graph_results=graph_results,
        question=question,
    )
