"""
graph/graph_query.py
────────────────────────────────────────────────────────────────────────────────
Query functions for reading from the Neo4j knowledge graph.

TWO PURPOSES:
  1. execute_cypher()  — Runs any Cypher query (used by Q&A: question → Cypher
                         → results → answer). This is the dynamic path.

  2. get_graph_data()  — Returns all nodes and edges in a format ready for
                         the Streamlit visualization frontend. This is the
                         static "show me everything" path.

HOW NEO4J RETURNS DATA:
  When you run:  MATCH (n)-[r]->(m) RETURN n, r, m
  Neo4j returns records containing Node and Relationship objects.
  These are not plain dicts — they have special neo4j types:
    - neo4j.graph.Node        → dict-like, has .labels, .element_id, .items()
    - neo4j.graph.Relationship → dict-like, has .type, .element_id, .items()

  We convert these to plain Python dicts before returning, so the api/
  layer doesn't need to know anything about neo4j types.

CYPHER INJECTION SAFETY NOTE:
  execute_cypher() runs generated Cypher strings (from Gemini).
  We don't validate the Cypher before running it — we trust that:
    a) The Gemini-generated Cypher is a MATCH query (read-only).
    b) The Neo4j user we connect with has read-only permissions (best practice).
  For production, consider using a read-only Neo4j user for Q&A queries.
────────────────────────────────────────────────────────────────────────────────
"""

import logging

from neo4j.graph import Node, Relationship

from graph.neo4j_client import Neo4jClient

logger = logging.getLogger(__name__)


def execute_cypher(cypher: str, params: dict | None = None) -> list[dict]:
    """
    Executes a Cypher query and returns results as a list of plain dicts.

    This is used by the Q&A pipeline:
      User question → Gemini generates Cypher → execute_cypher() → raw results
      → answer_generator() → human-readable answer.

    Args:
        cypher (str):
            The Cypher query to execute.
            This will typically be LLM-generated by cypher_generator.py.
            Example: "MATCH (p:Person)-[:CEO_OF]->(o:Organization)
                      RETURN p.name AS person, o.name AS org"

        params (dict | None):
            Optional query parameters. Use for any user-supplied values
            to prevent Cypher injection.

    Returns:
        list[dict]:
            Each dict is one result row with column names as keys.
            Neo4j Node and Relationship objects are converted to plain dicts.
            Returns [] if no results found.

    Example:
        results = execute_cypher(
            "MATCH (p:Person {name: $name})-[:WORKS_FOR]->(o) RETURN o.name",
            {"name": "Sam Altman"}
        )
        # → [{"o.name": "OpenAI"}]
    """
    client = Neo4jClient.get_instance()

    logger.info("Executing Cypher query: %s", cypher[:300])

    try:
        raw_records = client.run_query(cypher, params)
    except Exception as exc:
        logger.error("Cypher execution failed: %s | Query: %s", exc, cypher)
        raise

    # Convert any neo4j Node/Relationship objects to plain dicts
    results = [_flatten_record(record) for record in raw_records]

    logger.info("Cypher returned %d record(s)", len(results))
    return results


def get_graph_data(document_id: str | None = None) -> dict:
    """
    Returns all nodes and relationships in the graph, ready for visualization.

    This is used by:
      - GET /graph          → returns the entire graph
      - GET /graph/{doc_id} → returns only nodes from a specific document

    The output format is designed for the `streamlit-agraph` component:
      {
        "nodes": [
          {"id": "OpenAI", "label": "OpenAI", "type": "Organization"},
          ...
        ],
        "edges": [
          {"source": "OpenAI", "target": "GPT-4", "label": "CREATED"},
          ...
        ]
      }

    Args:
        document_id (str | None):
            If provided, filters to only nodes that have this document_id
            in their `document_ids` property.
            If None, returns the full graph.

    Returns:
        dict with keys "nodes" (list) and "edges" (list).
        Each node dict has: id, label, type.
        Each edge dict has: source, target, label.
    """
    client = Neo4jClient.get_instance()

    # ── Fetch nodes ───────────────────────────────────────────────────────────
    if document_id:
        node_cypher = """
            MATCH (n)
            WHERE $document_id IN n.document_ids
            RETURN
                n.name        AS name,
                labels(n)[0]  AS type,
                n.document_ids AS document_ids
        """
        node_params = {"document_id": document_id}
    else:
        node_cypher = """
            MATCH (n)
            RETURN
                n.name        AS name,
                labels(n)[0]  AS type,
                n.document_ids AS document_ids
        """
        node_params = {}

    raw_nodes = client.run_query(node_cypher, node_params)

    nodes = [
        {
            "id":    record.get("name", ""),
            "label": record.get("name", ""),
            "type":  record.get("type", "Entity"),
        }
        for record in raw_nodes
        if record.get("name")  # skip nodes with no name
    ]

    # ── Fetch edges ───────────────────────────────────────────────────────────
    if document_id:
        edge_cypher = """
            MATCH (a)-[r]->(b)
            WHERE $document_id IN a.document_ids
              AND $document_id IN b.document_ids
            RETURN
                a.name   AS source,
                b.name   AS target,
                type(r)  AS relation
        """
        edge_params = {"document_id": document_id}
    else:
        edge_cypher = """
            MATCH (a)-[r]->(b)
            RETURN
                a.name   AS source,
                b.name   AS target,
                type(r)  AS relation
        """
        edge_params = {}

    raw_edges = client.run_query(edge_cypher, edge_params)

    edges = [
        {
            "source": record.get("source", ""),
            "target": record.get("target", ""),
            "label":  record.get("relation", ""),
        }
        for record in raw_edges
        if record.get("source") and record.get("target")
    ]

    logger.info(
        "Graph data: %d nodes, %d edges (document_id=%s)",
        len(nodes), len(edges), document_id or "all",
    )

    return {"nodes": nodes, "edges": edges}


def _flatten_record(record: dict) -> dict:
    """
    Converts a Neo4j record dict to a plain Python dict.

    Neo4j can return special objects inside records:
      - neo4j.graph.Node         → convert to its properties dict
      - neo4j.graph.Relationship → convert to its properties dict + type

    This ensures the api/ layer receives only JSON-serializable types.

    Args:
        record (dict): A raw record dict from Neo4jClient.run_query().

    Returns:
        dict: A plain dict with all neo4j-specific types flattened.

    Example:
        Input:  {"n": <Node id=1 labels={'Person'} properties={'name': 'Sam'}>}
        Output: {"n": {"name": "Sam", "_labels": ["Person"]}}
    """
    flattened = {}
    for key, value in record.items():
        if isinstance(value, Node):
            # Convert Node to dict: its properties + labels
            node_dict = dict(value.items())
            node_dict["_labels"] = list(value.labels)
            flattened[key] = node_dict
        elif isinstance(value, Relationship):
            # Convert Relationship to dict: its properties + type
            rel_dict = dict(value.items())
            rel_dict["_type"] = value.type
            flattened[key] = rel_dict
        else:
            flattened[key] = value
    return flattened
